/* Run against tests/serve_ui.py only: temporary SQLite, no real customer data. */
const {chromium}=require('playwright');
const assert=require('node:assert/strict');
const fs=require('node:fs');const path=require('node:path');
const root=path.resolve(__dirname,'..');
const shots=path.join(root,'docs/screenshots');fs.mkdirSync(shots,{recursive:true});
const base=process.env.COFFEEFLOW_TEST_URL||'http://127.0.0.1:5016';
assert.ok(['127.0.0.1','localhost'].includes(new URL(base).hostname),'Use a local temporary QA server.');
const results=[];const errors=[];
let browser;
async function test(name,fn){await fn();results.push({name,status:'passed'});console.log('PASS',name);}
async function text(page,selector,value){await page.waitForFunction(({selector,value})=>document.querySelector(selector)?.textContent.includes(value),{selector,value});}
async function login(page){await page.goto(base+'/admin');await page.locator('#login-form').waitFor();await page.locator('[name=username]').fill('tester');await page.locator('[name=password]').fill('Ui-test-only-2026!');await page.locator('#login-form button').click();await page.locator('#admin-app').waitFor();await page.locator('#admin-orders-list .loading').waitFor({state:'hidden'});}
async function noOverflow(page){assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'Horizontal overflow');}
async function main(){
 browser=await chromium.launch({headless:true,...(process.env.BROWSER_EXECUTABLE?{executablePath:process.env.BROWSER_EXECUTABLE}:{})});
 const context=await browser.newContext({viewport:{width:1440,height:1000}});
 const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));let orderURL;
 await test('Desktop menu loads real API products',async()=>{await page.goto(base);await page.locator('.product-card').first().waitFor();assert.equal(await page.locator('.product-card').count(),3);await noOverflow(page);await page.screenshot({path:path.join(shots,'01-menu-desktop.png'),fullPage:true});});
 await test('Categories and empty search results',async()=>{await page.getByRole('button',{name:'Десерти',exact:true}).click();assert.equal(await page.locator('.product-card').count(),1);await page.locator('#search').fill('неіснуюча кава');await text(page,'#catalog','Нічого не знайшли');await page.locator('#search').fill('');await page.getByRole('button',{name:'Усе меню',exact:true}).click();});
 await test('Cart add, quantity, removal and persistence',async()=>{await page.getByRole('button',{name:'Додати Еспресо до кошика',exact:true}).click();await page.getByRole('button',{name:'Збільшити кількість Еспресо',exact:true}).click();await text(page,'#cart-total','90');await page.reload();await page.locator('.product-card').first().waitFor();await text(page,'#cart-total','90');await page.getByRole('button',{name:'Додати Чизкейк до кошика',exact:true}).click();await page.locator('[data-remove="3"]').click();await text(page,'#cart-total','90');await page.screenshot({path:path.join(shots,'03-cart.png'),fullPage:true});});
 await test('Checkout validation blocks invalid phone',async()=>{await page.locator('#checkout-link').click();await page.locator('#checkout-layout').waitFor();await page.locator('[name=customer_name]').fill('Тестовий клієнт');await page.locator('[name=phone]').fill('123');await page.locator('#place-order').click();assert.equal(await page.locator('[name=phone]').evaluate(e=>e.validity.valid),false);assert.ok(page.url().endsWith('/checkout'));await page.locator('[name=phone]').fill('+380501234567');await page.screenshot({path:path.join(shots,'04-checkout.png'),fullPage:true});});
 await test('Server validation retains entered form values',async()=>{const csrf=await context.request.get(base+'/api/v1/auth/csrf');assert.equal(csrf.status(),200);await page.locator('[name=comment]').fill('Рядок 1\nРядок 2');await page.locator('#place-order').click();await page.locator('#form-error').waitFor();assert.equal(await page.locator('[name=customer_name]').inputValue(),'Тестовий клієнт');await page.locator('[name=comment]').fill('');});
 await test('Real checkout creates one order and clears cart',async()=>{let writes=0;page.on('request',r=>{if(r.method()==='POST'&&r.url()===base+'/api/v1/orders')writes++;});await page.locator('#place-order').click();await page.waitForURL(/\/orders\/\d+\?created=1/);await page.locator('.order-card').waitFor();orderURL=page.url().split('?')[0];await text(page,'.order-card','90');assert.equal(writes,1);assert.equal(await page.locator('#cart-count').textContent(),'0');await page.screenshot({path:path.join(shots,'05-order.png'),fullPage:true});});
 await test('Other guest cannot see private order',async()=>{const other=await browser.newContext();const p=await other.newPage();await p.goto(orderURL);await text(p,'#orders-list','недоступне');await other.close();});
 await test('Wrong admin password and successful login',async()=>{await page.goto(base+'/admin');await page.locator('#login-form').waitFor();await page.locator('[name=username]').fill('tester');await page.locator('[name=password]').fill('wrong');await page.locator('#login-form button').click();await text(page,'#login-error','Неправильний');await page.locator('[name=password]').fill('Ui-test-only-2026!');await page.locator('#login-form button').click();await page.locator('#admin-app').waitFor();await page.locator('#admin-orders-list .order-card').first().waitFor();});
 await test('Admin changes order status through PATCH',async()=>{const id=new URL(orderURL).pathname.split('/').pop();await page.locator(`[data-status=accepted][data-id="${id}"]`).click();await text(page,`[data-order="${id}"] .badge`,'Прийнято');await page.screenshot({path:path.join(shots,'06-admin-orders.png'),fullPage:true});});
 await test('Category create/edit/delete and conflict error',async()=>{await page.locator('#tab-categories').click();await page.locator('#new-category').click();await page.locator('#editor [name=name]').fill('Тестова категорія');await page.locator('#editor-form button[type=submit]').click();await page.locator('#editor').waitFor({state:'hidden'});const row=page.locator('.category-row').filter({hasText:'Тестова категорія'});await row.waitFor();await row.getByRole('button',{name:'Редагувати'}).click();await page.locator('#editor [name=name]').fill('Тестова змінена');await page.locator('#editor-form button[type=submit]').click();await page.locator('#editor').waitFor({state:'hidden'});page.once('dialog',d=>d.accept());await page.locator('.category-row').filter({hasText:'Тестова змінена'}).getByRole('button',{name:'Видалити'}).click();await page.locator('.category-row').filter({hasText:'Тестова змінена'}).waitFor({state:'hidden'});page.once('dialog',d=>d.accept());await page.locator('.category-row').filter({hasText:'Кава'}).getByRole('button',{name:'Видалити'}).click();await text(page,'#admin-error','Категорія має товари');});
 await test('Product create/edit/delete through real API',async()=>{await page.locator('#tab-products').click();await page.locator('#new-product').click();await page.locator('#editor [name=name]').fill('Тестове лате');await page.locator('#editor [name=price]').fill('72.50');await page.locator('#editor-form button[type=submit]').click();await page.locator('#editor').waitFor({state:'hidden'});const card=page.locator('#admin-product-list article').filter({hasText:'Тестове лате'});await card.waitFor();await card.getByRole('button',{name:'Редагувати'}).click();await page.locator('#editor [name=price]').fill('75.25');await page.locator('#editor [name=is_available]').uncheck();await page.locator('#editor-form button[type=submit]').click();await page.locator('#editor').waitFor({state:'hidden'});await card.getByText('Немає в наявності').waitFor();await page.screenshot({path:path.join(shots,'07-admin-menu.png'),fullPage:true});page.once('dialog',d=>d.accept());await card.getByRole('button',{name:'Прибрати з меню'}).click();await card.waitFor({state:'hidden'});});
 await test('Logout protects administrative screens',async()=>{await page.locator('#logout').click();await page.locator('#login-form').waitFor();assert.equal(await page.locator('#admin-app').isVisible(),false);});
 await test('Customer refresh sees updated order status',async()=>{await page.goto(orderURL);await text(page,'.order-card .badge','Прийнято');});
 await test('Responsive layout at 390 and 768 pixels',async()=>{await page.setViewportSize({width:390,height:844});await page.goto(base);await page.locator('.product-card').first().waitFor();await noOverflow(page);await page.screenshot({path:path.join(shots,'02-menu-mobile.png'),fullPage:true});await page.getByRole('button',{name:'Додати Еспресо до кошика',exact:true}).click();await page.goto(base+'/checkout');await page.locator('#checkout-layout').waitFor();await noOverflow(page);await page.screenshot({path:path.join(shots,'08-checkout-mobile.png'),fullPage:true});await page.setViewportSize({width:768,height:1024});await page.goto(base);await page.locator('.product-card').first().waitFor();await noOverflow(page);});
 await test('Loading state and API 503 error with recovery (injected)',async()=>{await page.route('**/api/v1/products?*',async route=>{await new Promise(r=>setTimeout(r,700));await route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({error:{message:'Тест: сервіс тимчасово недоступний',code:'database_unavailable'}})});});await page.goto(base);await page.getByText('Завантажуємо меню…',{exact:true}).waitFor();await text(page,'#catalog','Тест: сервіс');await page.unroute('**/api/v1/products?*');await page.locator('#catalog').getByRole('button',{name:'Повторити'}).click();await page.locator('.product-card').first().waitFor();});
 await test('Network error and empty catalog (injected)',async()=>{await page.route('**/api/v1/products?*',route=>route.abort('failed'));await page.goto(base);await text(page,'#catalog','Не вдалося отримати відповідь');await page.unroute('**/api/v1/products?*');await page.route('**/api/v1/products?*',route=>route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({items:[],total:0,limit:100,offset:0})}));await page.goto(base);await text(page,'#catalog','Меню ще готується');await page.unroute('**/api/v1/products?*');});
 await test('Unavailable product blocks checkout (injected)',async()=>{await page.route('**/api/v1/products?*',async route=>{const response=await route.fetch();const data=await response.json();data.items.forEach(p=>p.is_available=false);await route.fulfill({response,json:data});});await page.goto(base+'/checkout');await text(page,'#checkout-state','більше недоступні');assert.equal(await page.locator('#checkout-form').isVisible(),false);await page.unroute('**/api/v1/products?*');});
 await test('No uncaught JavaScript errors',async()=>assert.deepEqual(errors,[]));
 await context.close();
}
main().then(()=>{fs.writeFileSync(path.join(root,'docs/frontend-test-results.json'),JSON.stringify({date:new Date().toISOString(),browser:'Chromium via Playwright',results},null,2));console.log(`TOTAL ${results.length} passed`);}).catch(error=>{console.error(error);process.exitCode=1;}).finally(async()=>{if(browser)await browser.close();});
